--liquibase formatted sql

--changeset Patrick Heidotting:1

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

CREATE TABLE IF NOT EXISTS `BIJLAGE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `BESTANDSNAAM` varchar(255) DEFAULT NULL,
  `POLIS` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK24236076E10F3258` (`POLIS`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `BIJLAGE_AUD` (
  `ID` bigint(20) NOT NULL,
  `REV` int(11) NOT NULL,
  `REVTYPE` tinyint(4) DEFAULT NULL,
  `BESTANDSNAAM` varchar(255) DEFAULT NULL,
  `POLIS` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`,`REV`),
  KEY `FKAA1E6347D04A6114` (`REV`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `GEBRUIKER` (
  `SOORT` varchar(1) NOT NULL,
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `EMAILADRES` varchar(255) DEFAULT NULL,
  `SALT` varchar(255) DEFAULT NULL,
  `WACHTWOORD` varchar(255) DEFAULT NULL,
  `ACHTERNAAM` varchar(255) DEFAULT NULL,
  `TUSSENVOEGSEL` varchar(255) DEFAULT NULL,
  `VOORNAAM` varchar(255) DEFAULT NULL,
  `HUISNUMMER` bigint(20) DEFAULT NULL,
  `PLAATS` varchar(255) DEFAULT NULL,
  `POSTCODE` varchar(6) DEFAULT NULL,
  `STRAAT` varchar(255) DEFAULT NULL,
  `TOEVOEGING` varchar(255) DEFAULT NULL,
  `BSN` varchar(255) DEFAULT NULL,
  `BURGERLIJKESTAAT` varchar(1) DEFAULT NULL,
  `GEBOORTEDATUM` date DEFAULT NULL,
  `GESLACHT` varchar(1) DEFAULT NULL,
  `OVERLIJDENSDATUM` date DEFAULT NULL,
  `KANTOOR` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK52C4AA36ED5811CD` (`KANTOOR`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=3 ;

CREATE TABLE IF NOT EXISTS `GEBRUIKER_AUD` (
  `SOORT` varchar(1) NOT NULL,
  `ID` bigint(20) NOT NULL,
  `REV` int(11) NOT NULL,
  `REVTYPE` tinyint(4) DEFAULT NULL,
  `ACHTERNAAM` varchar(255) DEFAULT NULL,
  `TUSSENVOEGSEL` varchar(255) DEFAULT NULL,
  `VOORNAAM` varchar(255) DEFAULT NULL,
  `HUISNUMMER` bigint(20) DEFAULT NULL,
  `PLAATS` varchar(255) DEFAULT NULL,
  `POSTCODE` varchar(6) DEFAULT NULL,
  `STRAAT` varchar(255) DEFAULT NULL,
  `TOEVOEGING` varchar(255) DEFAULT NULL,
  `BSN` varchar(255) DEFAULT NULL,
  `BURGERLIJKESTAAT` varchar(1) DEFAULT NULL,
  `GEBOORTEDATUM` date DEFAULT NULL,
  `GESLACHT` varchar(1) DEFAULT NULL,
  `OVERLIJDENSDATUM` date DEFAULT NULL,
  `KANTOOR` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`,`REV`),
  KEY `FKAF84CD07D04A6114` (`REV`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `KANTOOR` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `HUISNUMMER` bigint(20) DEFAULT NULL,
  `PLAATS` varchar(255) DEFAULT NULL,
  `POSTCODE` varchar(6) DEFAULT NULL,
  `STRAAT` varchar(255) DEFAULT NULL,
  `TOEVOEGING` varchar(255) DEFAULT NULL,
  `BTW_NUMMER` varchar(255) DEFAULT NULL,
  `DATUMOPRICHTING` date DEFAULT NULL,
  `EMAILADRES` varchar(255) DEFAULT NULL,
  `HUISNUMMER_FACTUUR` bigint(20) DEFAULT NULL,
  `PLAATS_FACTUUR` varchar(255) DEFAULT NULL,
  `POSTCODE_FACTUUR` varchar(255) DEFAULT NULL,
  `STRAAT_FACTUUR` varchar(255) DEFAULT NULL,
  `TOEVOEGING_FACTUUR` varchar(255) DEFAULT NULL,
  `KVK` bigint(20) DEFAULT NULL,
  `NAAM` varchar(255) DEFAULT NULL,
  `RECHTSVORM` varchar(4) DEFAULT NULL,
  `SOORTKANTOOR` varchar(3) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `KANTOOR_AUD` (
  `ID` bigint(20) NOT NULL,
  `REV` int(11) NOT NULL,
  `REVTYPE` tinyint(4) DEFAULT NULL,
  `HUISNUMMER` bigint(20) DEFAULT NULL,
  `PLAATS` varchar(255) DEFAULT NULL,
  `POSTCODE` varchar(6) DEFAULT NULL,
  `STRAAT` varchar(255) DEFAULT NULL,
  `TOEVOEGING` varchar(255) DEFAULT NULL,
  `BTW_NUMMER` varchar(255) DEFAULT NULL,
  `DATUMOPRICHTING` date DEFAULT NULL,
  `EMAILADRES` varchar(255) DEFAULT NULL,
  `HUISNUMMER_FACTUUR` bigint(20) DEFAULT NULL,
  `PLAATS_FACTUUR` varchar(255) DEFAULT NULL,
  `POSTCODE_FACTUUR` varchar(255) DEFAULT NULL,
  `STRAAT_FACTUUR` varchar(255) DEFAULT NULL,
  `TOEVOEGING_FACTUUR` varchar(255) DEFAULT NULL,
  `KVK` bigint(20) DEFAULT NULL,
  `NAAM` varchar(255) DEFAULT NULL,
  `RECHTSVORM` varchar(4) DEFAULT NULL,
  `SOORTKANTOOR` varchar(3) DEFAULT NULL,
  PRIMARY KEY (`ID`,`REV`),
  KEY `FKC6ED7A27D04A6114` (`REV`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `ONDERLINGERELATIES` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `RELATIESOORT` varchar(3) DEFAULT NULL,
  `RELATIE` bigint(20) NOT NULL,
  `RELATIE_MET` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FKDB5A5468DF4C9431` (`RELATIE`),
  KEY `FKDB5A5468E78AD54E` (`RELATIE_MET`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=3 ;

CREATE TABLE IF NOT EXISTS `ONDERLINGERELATIES_AUD` (
  `ID` bigint(20) NOT NULL,
  `REV` int(11) NOT NULL,
  `REVTYPE` tinyint(4) DEFAULT NULL,
  `RELATIESOORT` varchar(3) DEFAULT NULL,
  `RELATIE` bigint(20) DEFAULT NULL,
  `RELATIE_MET` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`,`REV`),
  KEY `FK43F60E39D04A6114` (`REV`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `OPMERKING` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `OPMERKING` text,
  `KANTOOR` bigint(20) DEFAULT NULL,
  `POLIS` bigint(20) DEFAULT NULL,
  `RELATIE` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK9B213750E10F3258` (`POLIS`),
  KEY `FK9B213750DF4C9431` (`RELATIE`),
  KEY `FK9B213750ED5811CD` (`KANTOOR`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `OPMERKING_AUD` (
  `ID` bigint(20) NOT NULL,
  `REV` int(11) NOT NULL,
  `REVTYPE` tinyint(4) DEFAULT NULL,
  `OPMERKING` text,
  `KANTOOR` bigint(20) DEFAULT NULL,
  `POLIS` bigint(20) DEFAULT NULL,
  `RELATIE` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`,`REV`),
  KEY `FK2E413D21D04A6114` (`REV`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `POLIS` (
  `SOORT` varchar(1) NOT NULL,
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `INGANGSDATUM` date DEFAULT NULL,
  `OMSCHRIJVING` varchar(255) DEFAULT NULL,
  `KENTEKEN` varchar(10) DEFAULT NULL,
  `SOORTAUTOVERZEKERING` varchar(10) DEFAULT NULL,
  `MAATSCHAPPIJ` bigint(20) NOT NULL,
  `RELATIE` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK48C681739B15F9C` (`MAATSCHAPPIJ`),
  KEY `FK48C6817DF4C9431` (`RELATIE`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `POLIS_AUD` (
  `SOORT` varchar(1) NOT NULL,
  `ID` bigint(20) NOT NULL,
  `REV` int(11) NOT NULL,
  `REVTYPE` tinyint(4) DEFAULT NULL,
  `INGANGSDATUM` date DEFAULT NULL,
  `OMSCHRIJVING` varchar(255) DEFAULT NULL,
  `MAATSCHAPPIJ` bigint(20) DEFAULT NULL,
  `RELATIE` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`,`REV`),
  KEY `FK9988B268D04A6114` (`REV`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `REKENINGNUMMER` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `BIC` varchar(255) DEFAULT NULL,
  `REKENINGNUMMER` varchar(255) DEFAULT NULL,
  `KANTOOR` bigint(20) DEFAULT NULL,
  `RELATIE` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK975128D5DF4C9431` (`RELATIE`),
  KEY `FK975128D5ED5811CD` (`KANTOOR`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `REKENINGNUMMER_AUD` (
  `ID` bigint(20) NOT NULL,
  `REV` int(11) NOT NULL,
  `REVTYPE` tinyint(4) DEFAULT NULL,
  `BIC` varchar(255) DEFAULT NULL,
  `REKENINGNUMMER` varchar(255) DEFAULT NULL,
  `KANTOOR` bigint(20) DEFAULT NULL,
  `RELATIE` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`,`REV`),
  KEY `FKC662E426D04A6114` (`REV`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `REVINFO` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `timestamp` bigint(20) NOT NULL,
  `userid` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=4 ;

CREATE TABLE IF NOT EXISTS `SESSIE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `BROWSER` varchar(255) DEFAULT NULL,
  `COOKIECODE` varchar(255) DEFAULT NULL,
  `DATUMGECREERD` datetime DEFAULT NULL,
  `DATUMLAATSTGEBRUIKT` datetime DEFAULT NULL,
  `IPADRES` varchar(255) DEFAULT NULL,
  `SESSIE` varchar(255) DEFAULT NULL,
  `GEBRUIKER` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK91958CCE98BB5B4D` (`GEBRUIKER`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `SESSIE_AUD` (
  `ID` bigint(20) NOT NULL,
  `REV` int(11) NOT NULL,
  `REVTYPE` tinyint(4) DEFAULT NULL,
  `BROWSER` varchar(255) DEFAULT NULL,
  `COOKIECODE` varchar(255) DEFAULT NULL,
  `DATUMGECREERD` datetime DEFAULT NULL,
  `DATUMLAATSTGEBRUIKT` datetime DEFAULT NULL,
  `IPADRES` varchar(255) DEFAULT NULL,
  `SESSIE` varchar(255) DEFAULT NULL,
  `GEBRUIKER` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`,`REV`),
  KEY `FK7F72A39FD04A6114` (`REV`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `TELEFOONNUMMER` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `TELEFOONNUMMERSOORT` varchar(255) DEFAULT NULL,
  `TELEFOONNUMMER` varchar(10) DEFAULT NULL,
  `RELATIE` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK143A3E26DF4C9431` (`RELATIE`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `TELEFOONNUMMER_AUD` (
  `ID` bigint(20) NOT NULL,
  `REV` int(11) NOT NULL,
  `REVTYPE` tinyint(4) DEFAULT NULL,
  `TELEFOONNUMMERSOORT` varchar(255) DEFAULT NULL,
  `TELEFOONNUMMER` varchar(10) DEFAULT NULL,
  `RELATIE` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`,`REV`),
  KEY `FKD32EE8F7D04A6114` (`REV`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `VERZEKERINGSMAATSCHAPPIJ` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAAM` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `NAAM` (`NAAM`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `VERZEKERINGSMAATSCHAPPIJ_AUD` (
  `ID` bigint(20) NOT NULL,
  `REV` int(11) NOT NULL,
  `REVTYPE` tinyint(4) DEFAULT NULL,
  `NAAM` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`,`REV`),
  KEY `FK55C05C5DD04A6114` (`REV`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
