package nl.lakedigital.djfc.domain;

public enum SoortEntiteit {
    AANGIFTE, BEDRIJF, BELASTINGZAKEN, COMMUNICATIEPRODUCT, CONTACTPERSOON, HYPOTHEEK, KANTOOR, IBAANGIFTE, JAARCIJFERS, POLIS, RELATIE, RISICOANALYSE, SCHADE;
}
